# ControlPanel Configuration ${version}
#
# List GameModes where the ControlPanel addon is disabled.
# Add one GameMode name per line, prefixed with '-'. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes: []
